; This file was auto-generated by drush make
core = 7.x
api = 2

projects[drupal][version] = 7.37

; Modules
projects[addressfield][version] = "1.1"
projects[admin_menu][version] = "3.0-rc5"
projects[backup_migrate][version] = "3.0"
projects[blockexport][version] = "1.0"
projects[ctools][version] = "1.7"
projects[ckeditor][version] = "1.16"
projects[commerce][version] = "1.11"
projects[entity][version] = "1.6"
projects[features][version] = "2.5"
projects[file_entity][version] = "2.0-beta1"
projects[fivestar][version] = "2.1"
projects[jquery_update][version] = "2.5"
projects[libraries][version] = "2.2"
projects[link][version] = "1.3"
projects[media][version] = "2.0-alpha4"
projects[module_filter][version] = "2.0"
projects[node_export][version] = "3.0"
projects[pathauto][version] = "1.2"
projects[properties][version] = "1.0-alpha1"
projects[retina_images][version] = "1.0-beta4"
projects[rules][version] = "2.9"
projects[shortcode][version] = "2.21"
projects[tb_megamenu][version] = "1.0-beta5"
projects[token][version] = "1.6"
projects[uuid][version] = "1.0-alpha6"
projects[views][version] = "3.11"
projects[votingapi][version] = "2.12"
projects[webform][version] = "4.8"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[Rhythm][download][type] = "get"
projects[Rhythm][download][url] = "https://github.com/crunchyinmilk/Krosae/blob/master/theme_only/rhythm.zip"
projects[Rhythm][type] = "theme"
projects[Rhythm][version] = "1.1"


; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "git"
libraries[ckeditor][download][url] = "https://github.com/crunchyinmilk/Krosae/tree/master/libraries/ckeditor.git"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"